// @ts-check
import 'dotenv/config'
import { defineConfig } from 'drizzle-kit'

/**
 * Drizzle Kit config.
 *
 * - Points at our schema file (which re-exports the Better Auth tables
 *   generated by `npx @better-auth/cli generate`).
 * - `out` is where `drizzle-kit generate` writes migration SQL.
 * - For dev we use `drizzle-kit push` (no migration file) for speed.
 *   Switch to `drizzle-kit generate` + `drizzle-kit migrate` for prod.
 */
export default defineConfig({
  dialect: 'postgresql',
  schema: './src/lib/db/schema.ts',
  out: './drizzle',
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
  verbose: true,
  strict: true,
})
